### ISSUE TITLE
需要优化：创建联盟链时出错时，返回的错误信息需要优化

### ISSUE THREAD

**Issue by WZJ-Study** [QOSGroup/qos#299]
### qos网络启动前未配置RootCA, 即以下命令未执行：
`qosd config-root-ca --qcp root.crt --qsc root.crt --indent`
### 若未配置Root  CA, 创建联盟链时，返回的错误信息为panic原始堆栈信息，过于冗长， 需要优化。
```
$ ./qoscli tx init-qcp --creator qcp --qcp.crt ~/qcp.crt --indent
Password to sign with 'qcp':
{
  "check_tx": {
    "code": 1,
    "log": "{\"codespace\":\"sdk\",\"code\":1,\"message\":\"checkTxStd recovered: runtime error: invalid memory address or nil pointer dereference\\nstack:\\ngoroutine 21675 [running]:\\nruntime/debug.Stack(0xc002d28450, 0xee2ba0, 0x1b01be0)\\n\\t/home/imuge/go/go/src/runtime/debug/stack.go:24 +0x9d\\ngithub.com/QOSGroup/qbase/baseabci.(*BaseApp).checkTxStd.func1(0xc002d28b90, 0x1301800, 0xc001d88de0, 0xc002cbc8c0, 0x10, 0xc002e06a50)\\n\\t/home/imuge/go/path/pkg/mod/github.com/!q!o!s!group/qbase@v0.2.1/baseabci/baseapp.go:431 +0x23a\\npanic(0xee2ba0, 0x1b01be0)\\n\\t/home/imuge/go/go/src/runtime/panic.go:522 +0x1b5\\ngithub.com/QOSGroup/kepler/cert.VerityCrt(0xc002d286c0, 0x1, 0x1, 0xf24700, 0xc002ef0720, 0x0, 0x2f64768c, 0xed4f05615, 0x0, 0x2f64768c, ...)\\n\\t/home/imuge/go/path/pkg/mod/github.com/!q!o!s!group/kepler@v0.6.0/cert/types.go:63 +0x132\\ngithub.com/QOSGroup/qos/module/qcp.TxInitQCP.ValidateData(0xc00258cd80, 0x14, 0x14, 0xc002ca0fc0, 0x1301800, 0xc001d89440, 0xc002cbc8c0, 0x12, 0x0, 0x0)\\n\\t/home/imuge/go/code/qos/module/qcp/txs.go:46 +0x3f4\\ngithub.com/QOSGroup/qbase/txs.(*TxStd).ValidateBasicData(0xc002e06a50, 0x1301800, 0xc001d88de0, 0xc002cbc8c0, 0x10, 0x12c6e01, 0xc0025426f0, 0xa, 0x1304a00, 0x3e8)\\n\\t/home/imuge/go/path/pkg/mod/github.com/!q!o!s!group/qbase@v0.2.1/txs/txstd.go:166 +0x16d\\ngithub.com/QOSGroup/qbase/baseabci.(*BaseApp).checkTxStd(0xc000916180, 0x1301800, 0xc001d88de0, 0xc002cbc8c0, 0x10, 0xc002e06a50, 0x0, 0x0, 0x0, 0x0, ...)\\n\\t/home/imuge/go/path/pkg/mod/github.com/!q!o!s!group/qbase@v0.2.1/baseabci/baseapp.go:441 +0x194\\ngithub.com/QOSGroup/qbase/baseabci.(*BaseApp).CheckTx(0xc000916180, 0xc0026e5680, 0x177, 0x177, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\\n\\t/home/imuge/go/path/pkg/mod/github.com/!q!o!s!group/qbase@v0.2.1/baseabci/baseapp.go:399 +0x4fb\\ngithub.com/tendermint/tendermint/abci/client.(*localClient).CheckTxAsync(0xc000a35440, 0xc0026e5680, 0x177, 0x177, 0x0)\\n\\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/abci/client/local_client.go:99 +0xc5\\ngithub.com/tendermint/tendermint/proxy.(*appConnMempool).CheckTxAsync(0xc000ad9410, 0xc0026e5680, 0x177, 0x177, 0x1)\\n\\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/proxy/app_conn.go:114 +0x51\\ngithub.com/tendermint/tendermint/mempool.(*Mempool).CheckTxWithInfo(0xc0008792b0, 0xc0026e5680, 0x177, 0x177, 0xc002ccccc0, 0xc002440000, 0x0, 0x0)\\n\\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/mempool/mempool.go:427 +0x25e\\ngithub.com/tendermint/tendermint/mempool.(*Mempool).CheckTx(...)\\n\\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/mempool/mempool.go:354\\ngithub.com/tendermint/tendermint/rpc/core.BroadcastTxCommit(0xc002ef04a0, 0xc0026e5680, 0x177, 0x177, 0x0, 0x0, 0x0)\\n\\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/rpc/core/mempool.go:213 +0x6b7\\nreflect.Value.call(0xed6000, 0x11a3e28, 0x13, 0x10136d9, 0x4, 0xc001d88720, 0x2, 0x2, 0x2, 0xc001d88720, ...)\\n\\t/home/imuge/go/go/src/reflect/value.go:447 +0x461\\nreflect.Value.Call(0xed6000, 0x11a3e28, 0x13, 0xc001d88720, 0x2, 0x2, 0x1, 0x1, 0x0)\\n\\t/home/imuge/go/go/src/reflect/value.go:308 +0xa4\\ngithub.com/tendermint/tendermint/rpc/lib/server.makeJSONRPCHandler.func1(0x12fcf00, 0xc002ef0480, 0xc002ff9e00)\\n\\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/rpc/lib/server/handlers.go:150 +0x51c\\ngithub.com/tendermint/tendermint/rpc/lib/server.handleInvalidJSONRPCPaths.func1(0x12fcf00, 0xc002ef0480, 0xc002ff9e00)\\n\\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/rpc/lib/server/handlers.go:171 +0x9c\\nnet/http.HandlerFunc.ServeHTTP(0xc000a37760, 0x12fcf00, 0xc002ef0480, 0xc002ff9e00)\\n\\t/home/imuge/go/go/src/net/http/server.go:1995 +0x44\\nnet/http.(*ServeMux).ServeHTTP(0xc000121180, 0x12fcf00, 0xc002ef0480, 0xc002ff9e00)\\n\\t/home/imuge/go/go/src/net/http/server.go:2375 +0x1d6\\ngithub.com/tendermint/tendermint/rpc/lib/server.maxBytesHandler.ServeHTTP(0x12e67c0, 0xc000121180, 0xf4240, 0x12fcf00, 0xc002ef0480, 0xc002ff9e00)\\n\\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/rpc/lib/server/http_server.go:185 +0xd0\\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1(0x12fd600, 0xc001b94700, 0xc002ff9e00)\\n\\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/rpc/lib/server/http_server.go:158 +0x317\\nnet/http.HandlerFunc.ServeHTTP(0xc000ade000, 0x12fd600, 0xc001b94700, 0xc002ff9e00)\\n\\t/home/imuge/go/go/src/net/http/server.go:1995 +0x44\\nnet/http.serverHandler.ServeHTTP(0xc0000ae680, 0x12fd600, 0xc001b94700, 0xc002ff9e00)\\n\\t/home/imuge/go/go/src/net/http/server.go:2774 +0xa8\\nnet/http.(*conn).serve(0xc001ef8b40, 0x1301740, 0xc002cdc680)\\n\\t/home/imuge/go/go/src/net/http/server.go:1878 +0x851\\ncreated by net/http.(*Server).Serve\\n\\t/home/imuge/go/go/src/net/http/server.go:2884 +0x2f4\\n\"}",
    "gasWanted": "100000",
    "gasUsed": "2108"
  },
  "deliver_tx": {},
  "hash": "1D73D5AFF4CF726D6D2D14E9AD2255F1538621D4F96F95C2996BE242479BCB3B",
  "height": "0"
}
ERROR: {"codespace":"sdk","code":1,"message":"checkTxStd recovered: runtime error: invalid memory address or nil pointer dereference\nstack:\ngoroutine 21675 [running]:\nruntime/debug.Stack(0xc002d28450, 0xee2ba0, 0x1b01be0)\n\t/home/imuge/go/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/QOSGroup/qbase/baseabci.(*BaseApp).checkTxStd.func1(0xc002d28b90, 0x1301800, 0xc001d88de0, 0xc002cbc8c0, 0x10, 0xc002e06a50)\n\t/home/imuge/go/path/pkg/mod/github.com/!q!o!s!group/qbase@v0.2.1/baseabci/baseapp.go:431 +0x23a\npanic(0xee2ba0, 0x1b01be0)\n\t/home/imuge/go/go/src/runtime/panic.go:522 +0x1b5\ngithub.com/QOSGroup/kepler/cert.VerityCrt(0xc002d286c0, 0x1, 0x1, 0xf24700, 0xc002ef0720, 0x0, 0x2f64768c, 0xed4f05615, 0x0, 0x2f64768c, ...)\n\t/home/imuge/go/path/pkg/mod/github.com/!q!o!s!group/kepler@v0.6.0/cert/types.go:63 +0x132\ngithub.com/QOSGroup/qos/module/qcp.TxInitQCP.ValidateData(0xc00258cd80, 0x14, 0x14, 0xc002ca0fc0, 0x1301800, 0xc001d89440, 0xc002cbc8c0, 0x12, 0x0, 0x0)\n\t/home/imuge/go/code/qos/module/qcp/txs.go:46 +0x3f4\ngithub.com/QOSGroup/qbase/txs.(*TxStd).ValidateBasicData(0xc002e06a50, 0x1301800, 0xc001d88de0, 0xc002cbc8c0, 0x10, 0x12c6e01, 0xc0025426f0, 0xa, 0x1304a00, 0x3e8)\n\t/home/imuge/go/path/pkg/mod/github.com/!q!o!s!group/qbase@v0.2.1/txs/txstd.go:166 +0x16d\ngithub.com/QOSGroup/qbase/baseabci.(*BaseApp).checkTxStd(0xc000916180, 0x1301800, 0xc001d88de0, 0xc002cbc8c0, 0x10, 0xc002e06a50, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/imuge/go/path/pkg/mod/github.com/!q!o!s!group/qbase@v0.2.1/baseabci/baseapp.go:441 +0x194\ngithub.com/QOSGroup/qbase/baseabci.(*BaseApp).CheckTx(0xc000916180, 0xc0026e5680, 0x177, 0x177, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/home/imuge/go/path/pkg/mod/github.com/!q!o!s!group/qbase@v0.2.1/baseabci/baseapp.go:399 +0x4fb\ngithub.com/tendermint/tendermint/abci/client.(*localClient).CheckTxAsync(0xc000a35440, 0xc0026e5680, 0x177, 0x177, 0x0)\n\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/abci/client/local_client.go:99 +0xc5\ngithub.com/tendermint/tendermint/proxy.(*appConnMempool).CheckTxAsync(0xc000ad9410, 0xc0026e5680, 0x177, 0x177, 0x1)\n\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/proxy/app_conn.go:114 +0x51\ngithub.com/tendermint/tendermint/mempool.(*Mempool).CheckTxWithInfo(0xc0008792b0, 0xc0026e5680, 0x177, 0x177, 0xc002ccccc0, 0xc002440000, 0x0, 0x0)\n\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/mempool/mempool.go:427 +0x25e\ngithub.com/tendermint/tendermint/mempool.(*Mempool).CheckTx(...)\n\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/mempool/mempool.go:354\ngithub.com/tendermint/tendermint/rpc/core.BroadcastTxCommit(0xc002ef04a0, 0xc0026e5680, 0x177, 0x177, 0x0, 0x0, 0x0)\n\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/rpc/core/mempool.go:213 +0x6b7\nreflect.Value.call(0xed6000, 0x11a3e28, 0x13, 0x10136d9, 0x4, 0xc001d88720, 0x2, 0x2, 0x2, 0xc001d88720, ...)\n\t/home/imuge/go/go/src/reflect/value.go:447 +0x461\nreflect.Value.Call(0xed6000, 0x11a3e28, 0x13, 0xc001d88720, 0x2, 0x2, 0x1, 0x1, 0x0)\n\t/home/imuge/go/go/src/reflect/value.go:308 +0xa4\ngithub.com/tendermint/tendermint/rpc/lib/server.makeJSONRPCHandler.func1(0x12fcf00, 0xc002ef0480, 0xc002ff9e00)\n\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/rpc/lib/server/handlers.go:150 +0x51c\ngithub.com/tendermint/tendermint/rpc/lib/server.handleInvalidJSONRPCPaths.func1(0x12fcf00, 0xc002ef0480, 0xc002ff9e00)\n\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/rpc/lib/server/handlers.go:171 +0x9c\nnet/http.HandlerFunc.ServeHTTP(0xc000a37760, 0x12fcf00, 0xc002ef0480, 0xc002ff9e00)\n\t/home/imuge/go/go/src/net/http/server.go:1995 +0x44\nnet/http.(*ServeMux).ServeHTTP(0xc000121180, 0x12fcf00, 0xc002ef0480, 0xc002ff9e00)\n\t/home/imuge/go/go/src/net/http/server.go:2375 +0x1d6\ngithub.com/tendermint/tendermint/rpc/lib/server.maxBytesHandler.ServeHTTP(0x12e67c0, 0xc000121180, 0xf4240, 0x12fcf00, 0xc002ef0480, 0xc002ff9e00)\n\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/rpc/lib/server/http_server.go:185 +0xd0\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1(0x12fd600, 0xc001b94700, 0xc002ff9e00)\n\t/home/imuge/go/path/pkg/mod/github.com/tendermint/tendermint@v0.31.5/rpc/lib/server/http_server.go:158 +0x317\nnet/http.HandlerFunc.ServeHTTP(0xc000ade000, 0x12fd600, 0xc001b94700, 0xc002ff9e00)\n\t/home/imuge/go/go/src/net/http/server.go:1995 +0x44\nnet/http.serverHandler.ServeHTTP(0xc0000ae680, 0x12fd600, 0xc001b94700, 0xc002ff9e00)\n\t/home/imuge/go/go/src/net/http/server.go:2774 +0xa8\nnet/http.(*conn).serve(0xc001ef8b40, 0x1301740, 0xc002cdc680)\n\t/home/imuge/go/go/src/net/http/server.go:1878 +0x851\ncreated by net/http.(*Server).Serve\n\t/home/imuge/go/go/src/net/http/server.go:2884 +0x2f4\n"}
```

**Comment by TokenxyWZY** [comment]
fix #332

**Comment by wangkuanzzu** [comment]
use qos version : branch->develop
The bug has been fixed and the result of verification as follows:
```
[vagrant@vagrant-192-168-1-201 ~]$ qoscli tx init-qcp --qcp.crt ./qosCA/qcp-zzu.crt --creator acc0
Password to sign with 'acc0':
{"check_tx":{"code":1,"log":"{\"codespace\":\"sdk\",\"code\":1,\"message\":\"TxStd's ITx ValidateData error:  ERROR:\\nCodespace: qcp\\nCode: 406\\nMessage: \\\"root ca not configure\\\"\\n\"}","gasWanted":"9223372036854775807","gasUsed":"1802114","events":[]},"deliver_tx":{},"hash":"B4CBE4A820615C63AFDF4A020C10B11D0DDA9CC0E5F06E21C8646BE64BEE5171","height":"0"}
ERROR: {"codespace":"sdk","code":1,"message":"TxStd's ITx ValidateData error:  ERROR:\nCodespace: qcp\nCode: 406\nMessage: \"root ca not configure\"\n"}
```
从测试结果可以看出提示信息为：root ca not configure
